version: "3"

services:
  db:
    container_name: recognizerBD
    hostname: recognizerBD
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --innodb_force_recovery=0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: recognizer
      MYSQL_ROOT_PASSWORD: paoDeBatata
